services:

  postgres:
    container_name: postgres
    image: postgres:15.3-alpine
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB
    networks:
      - custom

  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - custom

  sup_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - '.env'
    depends_on:
      - redis
    networks:
      - custom
    command: sh -c "alembic upgrade head && python -m src.main"
    ports:
      - "8080:8080"
    volumes:
      - .:/app

networks:
  custom:
    driver: bridge

volumes:
  redis_data:
