"""init second migrations

Revision ID: 2ffe033dd033
Revises: 036dc72013ae
Create Date: 2024-10-07 16:00:58.702020

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ffe033dd033'
down_revision: Union[str, None] = '036dc72013ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_category_id'), 'category', ['id'])
    op.drop_constraint('fk_category_owner_id_user', 'category', type_='foreignkey')
    op.drop_column('category', 'owner_id')
    op.create_unique_constraint(op.f('uq_meet_id'), 'meet', ['id'])
    op.create_unique_constraint(op.f('uq_participant_id'), 'participant', ['id'])
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    op.create_unique_constraint(op.f('uq_workspace_id'), 'workspace', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_workspace_id'), 'workspace', type_='unique')
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_participant_id'), 'participant', type_='unique')
    op.drop_constraint(op.f('uq_meet_id'), 'meet', type_='unique')
    op.add_column('category', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_category_owner_id_user', 'category', 'user', ['owner_id'], ['id'])
    op.drop_constraint(op.f('uq_category_id'), 'category', type_='unique')
    # ### end Alembic commands ###
